{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintTaneb where

-- pretty-printer generated by the BNF converter

import AbsTaneb
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print RNo where
  prt _ (RNo i) = doc (showString ( i))



instance Print Exp where
  prt i e = case e of
   IInt n -> prPrec i 0 (concatD [prt 0 n])
   INeg n -> prPrec i 1 (concatD [doc (showString "-") , prt 0 n])


instance Print Stm where
  prt i e = case e of
   Seqn stm0 stm -> prPrec i 0 (concatD [prt 1 stm0 , doc (showString ";") , prt 0 stm])
   Ifblk rno stm0 stm -> prPrec i 1 (concatD [doc (showString "T") , prt 0 rno , doc (showString "<") , prt 1 stm0 , doc (showString ">") , doc (showString "<") , prt 1 stm , doc (showString ">")])
   RAdd exp rno -> prPrec i 1 (concatD [prt 0 exp , doc (showString "A") , prt 0 rno])
   Whblk rno stm -> prPrec i 1 (concatD [doc (showString "N") , prt 0 rno , doc (showString "<") , prt 1 stm , doc (showString ">")])
   Prnt rno -> prPrec i 1 (concatD [doc (showString "E") , prt 0 rno])
   Prd rno -> prPrec i 1 (concatD [doc (showString "B") , prt 0 rno])



