module SkelTaneb where

-- Haskell module generated by the BNF converter

import AbsTaneb
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transRNo :: RNo -> Result
transRNo x = case x of
  RNo str  -> failure x


transExp :: Exp -> Result
transExp x = case x of
  IInt n  -> failure x
  INeg n  -> failure x


transStm :: Stm -> Result
transStm x = case x of
  Seqn stm1 stm2  -> failure x
  Ifblk rno stm1 stm2  -> failure x
  RAdd exp rno  -> failure x
  Whblk rno stm  -> failure x
  Prnt rno  -> failure x
  Prd rno  -> failure x



